// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace AjaxModuleTest.Models
{
    public partial class Course
    {
        private int? _courseID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CourseID
        {
            get { return this._courseID; }
            set { this._courseID = value; }
        }
        
        private int? _credits;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Credits
        {
            get { return this._credits; }
            set { this._credits = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Course class.
        /// </summary>
        public Course()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken courseIDValue = inputObject["CourseID"];
                if (courseIDValue != null && courseIDValue.Type != JTokenType.Null)
                {
                    this.CourseID = ((int)courseIDValue);
                }
                JToken creditsValue = inputObject["Credits"];
                if (creditsValue != null && creditsValue.Type != JTokenType.Null)
                {
                    this.Credits = ((int)creditsValue);
                }
                JToken titleValue = inputObject["Title"];
                if (titleValue != null && titleValue.Type != JTokenType.Null)
                {
                    this.Title = ((string)titleValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Course
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.CourseID != null)
            {
                outputObject["CourseID"] = this.CourseID.Value;
            }
            if (this.Credits != null)
            {
                outputObject["Credits"] = this.Credits.Value;
            }
            if (this.Title != null)
            {
                outputObject["Title"] = this.Title;
            }
            return outputObject;
        }
    }
}
